using StaticArrays

# 1. Sampling variables and events
# 1.1 Pathogen events, zooming out in scale (order matters)
# 1.1.1 Single pathogen, single host
const PATHOGEN_ESTABLISHMENT = 1
const CLEARANCE = 2
const RESPONSE_ACQUISITION = 3
# # 1.1.2 Two pathogens (symmetrical), single host
# const RECOMBINANT_ESTABLISHMENT = 4
# 1.1.2 Single pathogen, two hosts (asymmetrical)
const CONTACT = 4

# 1.2 Response events
# 1.2.1 Single response, single host
const RESPONSE_LOSS = 5

# 1.3 Host events
# 1.3.1 Single host, single population
const BIRTH = 6
const DEATH = 7
# 1.3.2 Single host, two populations (asymmetrical)
const TRANSITION = 8

# 1.4 Choice modifiers and second entity samplers, zooming in in scale (order matters)
# 1.4.1 Population choice
const RECEIVE_TRANSITION = 9

# 1.4.2 Host choice
const RECEIVE_CONTACT = 10

# 1.4.3 Pathogen choice
const INTRAHOST_FITNESS = 11

# 2. Non-sampling variables and sub-events, zooming out in scale
# 2.1 Pathogen-interaction sub-events
const GENERATIONS_PER_TRANSMISSION = 12
const MUTATIONS_PER_GENERATION = 13
const RECOMBINATIONS_PER_GENERATION = 14
const INOCULUM = 15
const TRANSMISSION_EFFICIENCY = 16
const VERTICAL_TRANSMISSION = 17
const RESPONSE_ACQUISITION_UPON_CLEARANCE = 18

# 2.2 Response-interaction sub-events
const RESPONSE_INHERITANCE = 19

# 2.3 Host-interaction sub-events
const HOST_MUTATIONS_UPON_BIRTH = 20
const HOST_RECOMBINATIONS_UPON_BIRTH = 21

# Global trackers
const PATHOGEN_EVENTS = SA[
    PATHOGEN_ESTABLISHMENT, CLEARANCE, RESPONSE_ACQUISITION, CONTACT
]
const NUM_PATHOGEN_EVENTS = length(PATHOGEN_EVENTS)

const RESPONSE_EVENTS = SA[RESPONSE_LOSS]
const NUM_RESPONSE_EVENTS = length(RESPONSE_EVENTS)

const HOST_EVENTS = SA[BIRTH, DEATH, TRANSITION]
const NUM_HOST_EVENTS = length(HOST_EVENTS)

const EVENTS = SA[PATHOGEN_EVENTS..., RESPONSE_EVENTS..., HOST_EVENTS...]
const NUM_EVENTS = length(EVENTS)

const CHOICE_MODIFIERS = SA[
    RECEIVE_TRANSITION, RECEIVE_CONTACT, INTRAHOST_FITNESS
]
const NUM_CHOICE_MODIFIERS = length(CHOICE_MODIFIERS)

const SAMPLING_COEFFICIENTS = SA[EVENTS..., CHOICE_MODIFIERS...]
const NUM_SAMPLING_COEFFICIENTS = length(SAMPLING_COEFFICIENTS)

const PATHOGEN_NONSAMPLING_COEFFICIENTS = SA[
    GENERATIONS_PER_TRANSMISSION,
    MUTATIONS_PER_GENERATION, RECOMBINATIONS_PER_GENERATION, INOCULUM,
    TRANSMISSION_EFFICIENCY, VERTICAL_TRANSMISSION,
    RESPONSE_ACQUISITION_UPON_CLEARANCE
]

const RESPONSE_NONSAMPLING_COEFFICIENTS = SA[RESPONSE_INHERITANCE]

const HOST_NONSAMPLING_COEFFICIENTS = SA[
    HOST_MUTATIONS_UPON_BIRTH, HOST_RECOMBINATIONS_UPON_BIRTH
]

const NONSAMPLING_COEFFICIENTS = SA[
    PATHOGEN_NONSAMPLING_COEFFICIENTS...,
    RESPONSE_NONSAMPLING_COEFFICIENTS..., HOST_NONSAMPLING_COEFFICIENTS...
]
const NUM_NONSAMPLING_COEFFICIENTS = length(NONSAMPLING_COEFFICIENTS)

const COEFFICIENTS = SA[SAMPLING_COEFFICIENTS..., NONSAMPLING_COEFFICIENTS...]
const NUM_COEFFICIENTS = length(COEFFICIENTS)

# History variable trackers
const UNINFECTED_NAIVE = 1
const UNINFECTED_IMMUNE = 2
const INFECTED_NAIVE = 3
const INFECTED_IMMUNE = 4
const DEAD = 5
const COMPARTMENTS = SA[
    UNINFECTED_NAIVE, UNINFECTED_IMMUNE,
    INFECTED_NAIVE, INFECTED_IMMUNE, DEAD
]
const NUM_COMPARTMENTS = length(COMPARTMENTS)

# Misc model constants
const CHROMOSOME_SEPARATOR = "/"
const HOMOLOGOUS_CHROMOSOME_SEPARATOR = "|"

# Output constants
const WITHIN_HOST_SEPARATOR = ";"
const PARENT_SEPARATOR = "+"
const COMPARTMENT_LABELS = [
    "Uninfected Naive", "Uninfected Immune", "Infected Naive",
    "Infected Immune", "Dead"
]

# Simulation constants
const ERROR_TOLERANCE = 1.0e-9
const RECALCULATION_EVENT_THRESHOLD = 100000
