using StaticArrays

const DEFAULT_PATHOGEN_TYPE = PathogenType(
    "Default",
    0,
    "", #"ARNDCEQGHILKMFPSTWYV*",
    SA[ # order defined in COEFFICIENTS
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
    ],
    SA[ # order defined in COEFFICIENTS
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
    ],
)

const DEFAULT_RESPONSE_TYPE = ResponseType(
    "Default",
    (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String) -> 1.0,
    SA[ # order defined in COEFFICIENTS
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
    ],
    SA[ # order defined in COEFFICIENTS
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
    ],
    SA[ # order defined in COEFFICIENTS
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
    ],
    SA[ # order defined in COEFFICIENTS
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
        (pat_g::String, imp_g::String, mat_g::String, hos_g::String, pop_id::String)->1.0,
    ],
)

const DEFAULT_HOST_TYPE = HostType(
    "Default",
    0,
    "", #"ARNDCEQGHILKMFPSTWYV*",
    SA[ # order defined in COEFFICIENTS
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
        (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0, (g::String,pop_id::String)->1.0,
    ],
)

const DEFAULT_POPULATION_TYPE = PopulationType(
    "Default",
    true,
    true,
    true,
    (h_1::String, h_2::String) -> true,
    SA[ # order defined in COEFFICIENTS
        0.0, 0.0, 0.0,
        0.0, 0.0, 0.0,
        0.0, 0.0, 1.0,
        0.0, 0.0, 1.0,
        1.0, 1.0, 1.0,
        1.0, 0.0, 0.0,
        0.0, 0.0, 0.0,
    ],
    pathogenFractionsWinnerTakesAll,
    weightedInteractionPathogenWinnerTakesAll,
    weightedInteractionResponseWinnerTakesAll,
    weightedInteractionHostwideProduct,
    (
        pathogen::Pathogen, host::Host,
        existing_responses::Dict{Tuple{String,String,String,String},Response},
        response_types::Dict{String,ResponseType},
        birth_time::Float64
    ) -> [deNovoResponse(
        pathogen, host, existing_responses, response_types, birth_time
    )],
    Dict{String,ResponseType}([(DEFAULT_RESPONSE_TYPE.id => DEFAULT_RESPONSE_TYPE)])
)
